@baseUrl = http://localhost:7111

### Login Request (Get a jwt token)
POST {{baseUrl}}/api/v2/auths/login HTTP/1.1
Content-Type: application/json

{
  "email": "saucebot@gmail.com",
  "password": "123456789"
}

### Register Request (create a new user)
POST {{baseUrl}}/api/v2/auths/register HTTP/1.1
Content-Type: application/json

{
  "email": "saucebot@gmail.com",
  "username": "saucebot",
  "password": "123456789"
}

### Get User details 
GET {{baseUrl}}/api/v2/auths/me HTTP/1.1
Content-Type: application/json
Cookie: access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZmFiNzc5LWRkOTEtNGFlNS04YTgzLTNlYzIwNTNmZmM4YiIsImlhdCI6MTczNjc2ODMxOSwiZXhwIjoxNzM2NzcxOTE5fQ.z4h2rtkJH8bizA0MQfXtcWUv3Wz2tOg2X4dOLmDcSas


### LOGOUT Request
DELETE {{baseUrl}}/api/v2/auths/logout HTTP/1.1
Content-Type: application/json


### ----- API FOR LOGIN ------
### Create a new login request
POST {{baseUrl}}/api/v2/logins/ HTTP/1.1
Content-Type: application/json
{
  "user_id": "a7b21447-fe9e-4de4-b4eb-ee75816c159c",
  "name": "Nerflix",
  "email": "saucebot@gmail.com",
  "username": "saucebot",
  "password": "123456789",
  "website": "www.nerflix.com",
  "folder_id": ""
}

### Get a login by id request
GET {{baseUrl}}/api/v2/logins/:id HTTP/1.1
Content-Type: application/json

### Update a login
PUT {{baseUrl}}/api/v2/logins/:id HTTP/1.1
Content-Type: application/json

### Delete a login 
DELETE {{baseUrl}}/api/v2/logins/:id HTTP/1.1
Content-Type: application/json

### ----- API FOR NOTES -----








