@baseUrl = http://localhost:6060

### Login Request
POST {{baseUrl}}/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "saucebot@gmail.com",
  "password": "123456789"
}

### Create New Login Request
POST {{baseUrl}}/api/logins/ HTTP/1.1
Content-Type: application/json

{
    "userUuid": "13af6aa8-055b-4038-b969-6f708a5295d2",
    "password":"123456789",
    "name": "Habitica",
    "username": "saucebot",
    "email": "saucebot@gmail.com",
    "password": "habitica_password",
    "website":"www.habitica.com"
}

### Get User By Id Request
POST {{baseUrl}}/api/logins/ HTTP/1.1
Content-Type: application/json

{
    "userUuid": "60969fa0-0fd9-4c19-ba43-4e02ad1e2e48",
    "password":"123456789",
    "name": "Disney Plus",
    "username": "saucebot",
    "email": "saucebot@gmail.com",
    "password": "123456789",
    "website":"www.disneyPlus.com"
}

### DECRYPT A PASSWORD
POST {{baseUrl}}/api/logins/decryptpassword HTTP/1.1
Content-Type: application/json

{
    "iv": "2045c6cad6b962f2344de1ea1e15f826",
    "password": "619e729fe5e1abed7a4af25dc4c9d14a"
}